version: "3.8"

services:
  app:
    container_name: bookingdh-dev
    image: bookingdh-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000


 

# docker-compose up 
# docker-compose logs -f
# docker-compose down
