version: "3.8"
services:
  mysql-dh:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "dh"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "root"
    volumes:
      - "./DH_Query.sql:/docker-entrypoint-initdb.d/DH_Query.sql"

  bookingdigital:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql-dh
    environment:
      MYSQL_HOTS: "mysql-dh"
      MYSQL_PORT: "3307"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "dh"

#  docker-compose up --build
