#cloud-config
packages:
  - docker.io
runcmd:
  - sudo yum update -y
  - sudo yum install -y docker
  - sudo systemctl start docker
  - sudo systemctl enable docker
  - docker pull luischdu/frontendbookingdh:1.2
  - docker run -p 80:80 --name client-bookingdh luischdu/frontendbookingdh:1.2